spring:
  application:
    name: usuarios
  datasource:
    url: jdbc:mysql://localhost:3306/laganga
    username: root
    password: robledo2007
    dirver-class-name: com.mysql.cj.jdbc.dirver
  jpa:
    # ORM de java
    hibernate:
      # Actualizacion de la base de datos basada en la entity
      ddl-auto: none
    # Visualizar
    show-sql: true
    database-patform: org.hibernate.dialect.MySQLDialect

Server:
  port: 9090
  servlet:
    context-path: /api/v1
